version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo Installing dependencies...
      - cd frontend
      - npm install

  pre_build:
    commands:
      - echo Running tests...
      - npm test -- --watchAll=false --testEnvironment=jsdom

  build:
    commands:
      - echo Building the frontend...
      - npm run build
      - echo Build completed on `date`
      
  post_build:
    commands:
      - echo Copying deployspec.yml to expected location...
      - echo "Current directory: $(pwd)"
      - echo "Files in current directory: $(ls -la)"
      - echo "Files in frontend directory: $(ls -la frontend)"
      - mkdir -p /codebuild/output/src2785146540/src/frontend/ || true
      - cp frontend/deployspec.yml /codebuild/output/src2785146540/src/frontend/ || echo "Failed to copy deployspec.yml, continuing anyway"
      - echo "Contents of target directory (if accessible): $(ls -la /codebuild/output/src2785146540/src/frontend/ 2>/dev/null || echo 'Cannot access target directory')"

artifacts:
  base-directory: frontend/build
  files:
    - '**/*'

cache:
  paths:
    - 'frontend/node_modules/**/*' 