version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo "Installing dependencies..."
      - pwd
      # If running from the root directory or frontend directory
      - if [ -d "frontend" ]; then
      - cd frontend
      - elif [ -d "../frontend" ]; then
      - cd ../frontend
      - fi
      - npm install

  pre_build:
    commands:
      - echo "Running tests..."
      - npm test -- --watchAll=false --testEnvironment=jsdom

  build:
    commands:
      - echo "Building the frontend..."
      - npm run build
      - echo "Build completed on `date`"
      
  post_build:
    commands:
      - echo "Post-build phase completed successfully"

artifacts:
  base-directory: frontend/build
  files:
    - '**/*'

cache:
  paths:
    - 'frontend/node_modules/**/*' 