version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo Installing dependencies...
      - cd frontend
      - npm install

  pre_build:
    commands:
      - echo Running tests...
      - npm test -- --watchAll=false

  build:
    commands:
      - echo Building the frontend...
      - npm run build
      - echo Build completed on `date`

artifacts:
  base-directory: frontend/build
  files:
    - '**/*'

cache:
  paths:
    - 'frontend/node_modules/**/*' 