version: 0.2
# Root-level buildspec.yml that works for both CodeBuild and CodeDeploy

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo "Installing dependencies"
  
  pre_build:
    commands:
      - echo "Running pre-build steps"
  
  build:
    commands:
      - echo "Building the application"
      - cd frontend && npm install && npm run build || echo "Build failed but continuing"
  
  post_build:
    commands:
      - echo "Post-build completed"

artifacts:
  files:
    - appspec.yml
    - scripts/**/*
    - frontend/build/**/*
  discard-paths: no

cache:
  paths:
    - 'frontend/node_modules/**/*' 